spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:mysql://google/normas?createDatabaseIfNotExist=true&cloudSqlInstance=sigo-308502:southamerica-east1:sigo&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
    username: root
    password: 123456
    schema: classpath*:db/schema.sql
    #data: classpath*:db/data.sql
    continue-on-error: true
    initialization-mode: always
