service: normas
runtime: java11
instance_class: F2
automatic_scaling:
  max_instances: 2
  target_throughput_utilization: 0.8
  max_concurrent_requests: 50
  max_pending_latency: 1200ms
  min_pending_latency: 1000ms
#instance_class: B4
#basic_scaling:
#  max_instances: 2
#  idle_timeout: 3m
